import fs from 'node:fs'

const root=process.cwd()
const mainPath=`${root}/src/main.tsx`
let main=fs.readFileSync(mainPath,'utf8')
const start=main.indexOf('function Entertainment({lang}:{lang:Lang}){')
const end=main.indexOf('\nfunction App(){',start)
if(start<0||end<0)throw new Error('Entertainment function markers not found')
const entertainment=`function Entertainment({lang}:{lang:Lang}){
  const [active,setActive]=useState<'podcast'|'music'|'video'>('podcast')
  const [video,setVideo]=useState({youtubeVideoId:'v9qaddGKum8',bilibiliBvid:'BV18nbE6kE18'})
  const [musicData,setMusicData]=useState<any[]>([])
  const [currentTrack,setCurrentTrack]=useState<string|null>(null)
  const [currentTitle,setCurrentTitle]=useState('')
  const [playing,setPlaying]=useState(false)
  const [progress,setProgress]=useState(0)
  const [duration,setDuration]=useState(0)
  const [audioError,setAudioError]=useState(false)
  const audioRef=useRef<HTMLAudioElement|null>(null)
  useEffect(()=>{fetch(\`${'${'}import.meta.env.BASE_URL}video-data.json\`).then(r=>r.ok?r.json():null).then(data=>{if(data)setVideo(v=>({...v,...data}))}).catch(()=>{})},[])
  useEffect(()=>{fetch(\`${'${'}import.meta.env.BASE_URL}music-data.json\`).then(r=>r.ok?r.json():null).then(data=>{if(Array.isArray(data?.albums))setMusicData(data.albums)}).catch(()=>{})},[])
  useEffect(()=>{const audio=audioRef.current;if(!audio)return;const onTime=()=>setProgress(audio.duration?audio.currentTime/audio.duration:0);const onLoaded=()=>setDuration(audio.duration||0);const onPlay=()=>setPlaying(true);const onPause=()=>setPlaying(false);const onEnded=()=>{setPlaying(false);setProgress(0)};const onError=()=>{setPlaying(false);setAudioError(true)};audio.addEventListener('timeupdate',onTime);audio.addEventListener('loadedmetadata',onLoaded);audio.addEventListener('play',onPlay);audio.addEventListener('pause',onPause);audio.addEventListener('ended',onEnded);audio.addEventListener('error',onError);return()=>{audio.removeEventListener('timeupdate',onTime);audio.removeEventListener('loadedmetadata',onLoaded);audio.removeEventListener('play',onPlay);audio.removeEventListener('pause',onPause);audio.removeEventListener('ended',onEnded);audio.removeEventListener('error',onError)}},[])
  const albums=[{zh:'牛马假日',en:'NiúMǎ Holiday',id:'385484900',year:'2026'},{zh:'池塘里的那片海',en:'The Sea in the Pond',id:'385484965',year:'2026'}]
  const nav=[{key:'podcast' as const,en:'Podcast',zh:'播客'},{key:'music' as const,en:'Original Music',zh:'原创音乐'},{key:'video' as const,en:'Video',zh:'影像'}]
  const playTrack=async(track:any)=>{const audio=audioRef.current;if(!audio)return;if(currentTrack===String(track.id)){if(audio.paused){setAudioError(false);try{await audio.play()}catch{setPlaying(false)}}else audio.pause();return}audio.pause();audio.src='https://music.163.com/song/media/outer/url?id='+track.id+'.mp3';audio.currentTime=0;setCurrentTrack(String(track.id));setCurrentTitle(track.name||'');setProgress(0);setDuration(0);setAudioError(false);try{await audio.play()}catch{setPlaying(false)}}
  return <main className="page entertainment-page"><PageTitle no="02" lang={lang} en="OneStage Entertainment" zh="壹阶娱乐" descEn="Podcast / Music / Video" descZh="播客 / 音乐 / 影像"/><div className="entertainment-category-nav">{nav.map(item=><button key={item.key} className={active===item.key?'selected':''} onClick={()=>{setActive(item.key);window.scrollTo({top:0,behavior:'smooth'})}}>{lang==='en'?item.en:item.zh}</button>)}</div>
    {active==='podcast'&&<section className="entertainment-tab-content"><section className="show-intro"><div><p className="eyebrow">ORIGINAL PODCAST</p><h2>{lang==='en'?'NiúMǎ Holiday':'牛马假日'}</h2><p className="show-desc">{lang==='en'?'A podcast documenting the lives, work and small absurdities of ordinary working people.':'一档记录普通打工人故事的播客。聊工作，也聊生活，以及那些发生在“牛马”与“假日”之间的真实切片。'}</p></div><div className="show-meta"><span>01 / ONESTAGE ENTERTAINMENT</span><span>{lang==='en'?'AUDIO PODCAST':'音频播客'}</span></div></section><EpisodeList lang={lang}/></section>}
    {active==='music'&&<section className="music-section entertainment-tab-content"><audio ref={audioRef} preload="none"/><div className="section-label"><span>{lang==='en'?'ORIGINAL MUSIC':'原创音乐'}</span><span>{lang==='en'?'NETEASE CLOUD MUSIC':'网易云音乐'}</span></div><div className="music-grid">{albums.map(album=>{const live=musicData.find(x=>String(x.id)===album.id);const tracks=Array.isArray(live?.tracks)?live.tracks:[];return <article className="music-card" key={album.id}><div className="music-card-head"><div><h3>{lang==='en'?album.en:album.zh}</h3><p>{lang==='en'?'Album · Rainchen · '+album.year:'专辑 · 雨尘 · '+album.year}</p></div></div>{tracks.length>0?<div className="music-tracks">{tracks.map((track:any)=><div className={'music-track '+(currentTrack===String(track.id)?'active':'')} key={track.id}><button className="music-track-button" onClick={()=>playTrack(track)} aria-label={currentTrack===String(track.id)&&playing?'Pause '+track.name:'Play '+track.name}><span className="music-track-play">{currentTrack===String(track.id)&&playing?'Ⅱ':'▶'}</span><span className="music-track-name">{track.name}</span><span className="music-track-arrow">↗</span></button>{currentTrack===String(track.id)&&<div className="music-track-player"><div className="music-track-progress"><span style={{width:(progress*100)+'%'}}/></div><span className="music-track-time">{duration?Math.floor((duration*(1-progress))/60).toString().padStart(2,'0')+':'+Math.floor((duration*(1-progress))%60).toString().padStart(2,'0'):'--:--'}</span>{audioError&&<a href={'https://music.163.com/#/song?id='+track.id} target="_blank" rel="noreferrer">Open in NetEase ↗</a>}</div>}</div>)}</div>:<div className="music-unavailable"><span>{lang==='en'?'Loading official tracks…':'正在加载歌曲…'}</span></div>}<a className="music-link-card" href={'https://music.163.com/album/'+album.id+'/?userid=310622971'} target="_blank" rel="noreferrer"><span>{lang==='en'?'OPEN ALBUM ON NETEASE CLOUD MUSIC':'在网易云音乐打开专辑'}</span><b>↗</b></a></article>})}</div></section>}
    {active==='video'&&<section className="video-tab-content entertainment-tab-content"><div className="section-label"><span>{lang==='en'?'LATEST VIDEO':'最新视频'}</span><span>{lang==='en'?'YOUTUBE':'BILIBILI'}</span></div>{lang==='en'?<div className="video-embed"><iframe title="NiúMǎ Holiday latest video on YouTube" src={'https://www.youtube.com/embed/'+video.youtubeVideoId+'?rel=0'} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div>:<div className="video-embed"><iframe title="牛马假日 latest video on Bilibili" src={'https://player.bilibili.com/player.html?bvid='+video.bilibiliBvid+'&autoplay=0&danmaku=0'} loading="lazy" allowFullScreen/></div>}<p className="feed-note">{lang==='en'?'Latest video · YouTube':'最新视频 · Bilibili'}</p></section>}
    <section className="platform-row"><span>{lang==='en'?'ALSO AVAILABLE ON':'同步发布于'}</span><span>{lang==='en'?'Xiaoyuzhou · Himalaya · Apple Podcasts · YouTube · Bilibili':'小宇宙 · 喜马拉雅 · Apple Podcasts · YouTube · Bilibili'}</span></section></main>
}
`
main=main.slice(0,start)+entertainment+main.slice(end)
fs.writeFileSync(mainPath,main)
console.log('Removed visible single-track playback note; playback exclusivity remains implemented.')
